/**
 * Hook Lab domain types.
 *
 * The pipeline stage between an Idea and a ContentDraft: take one idea and work
 * out its opening line. Candidates are generated by the AI provider (advisory)
 * or written by the user; every candidate is then scored by deterministic,
 * reproducible checks. No AI is involved in the scoring.
 */

import type { HookStrategy, HookSource } from "@/generated/prisma";

export type { HookStrategy, HookSource };

/** A deterministic clarity/readability note shown under a candidate. */
export interface ClarityNote {
  label: string;
  status: "pass" | "warn";
  detail: string;
}

export type HookWarningCode =
  "unverified-figure" | "too-long" | "too-short" | "multi-sentence" | "placeholder";

export interface HookWarning {
  code: HookWarningCode;
  message: string;
}

/** The frozen-at-insert evaluation of one hook candidate. */
export interface HookEvaluation {
  strategy: HookStrategy;
  relevanceScore: number; // 0-100
  relevanceOverlap: string[];
  clarityScore: number; // 0-100
  clarityGrade: "clear" | "okay" | "dense";
  clarityNotes: ClarityNote[];
  wordCount: number;
  warnings: HookWarning[];
}

/** Context a candidate is judged against — all from the idea, nothing invented. */
export interface HookContext {
  /** Idea title + angle, for relevance. */
  ideaText: string;
  /** Idea topics (from the KnowledgeProfile via the signal), for relevance. */
  topics: string[];
  /** Idea notes + source material: the only place a figure may legitimately
   *  come from. Used to flag unverified numbers. */
  factText: string;
}

export class HookLabError extends Error {
  constructor(
    public code: "not_found" | "ai_disabled" | "invalid" | "rate_limited" | "ai_failed",
    message: string,
  ) {
    super(message);
    this.name = "HookLabError";
  }
}
